//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDAD
    {
        public CIUDAD()
        {
            this.VENDEDOR = new HashSet<VENDEDOR>();
        }
    
        public int CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<VENDEDOR> VENDEDOR { get; set; }
    }
}
