//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.DataAccess.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<VENDEDOR> VENDEDOR { get; set; }
    
        public virtual int del_CIUDAD(Nullable<int> cODIGO)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_CIUDAD", cODIGOParameter);
        }
    
        public virtual int del_VENDEDOR(Nullable<int> cODIGO)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_VENDEDOR", cODIGOParameter);
        }
    
        public virtual ObjectResult<get_CIUDAD_Result> get_CIUDAD(Nullable<int> cODIGO)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_CIUDAD_Result>("get_CIUDAD", cODIGOParameter);
        }
    
        public virtual ObjectResult<get_VENDEDOR_Result> get_VENDEDOR(Nullable<int> cODIGO)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_VENDEDOR_Result>("get_VENDEDOR", cODIGOParameter);
        }
    
        public virtual int ins_CIUDAD(ObjectParameter cODIGO, string dESCRIPCION)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_CIUDAD", cODIGO, dESCRIPCIONParameter);
        }
    
        public virtual int ins_VENDEDOR(ObjectParameter cODIGO, string nOMBRE, string aPELLIDO, Nullable<long> nUMERO_IDENTIFICACION, Nullable<int> cODIGO_CIUDAD)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var nUMERO_IDENTIFICACIONParameter = nUMERO_IDENTIFICACION.HasValue ?
                new ObjectParameter("NUMERO_IDENTIFICACION", nUMERO_IDENTIFICACION) :
                new ObjectParameter("NUMERO_IDENTIFICACION", typeof(long));
    
            var cODIGO_CIUDADParameter = cODIGO_CIUDAD.HasValue ?
                new ObjectParameter("CODIGO_CIUDAD", cODIGO_CIUDAD) :
                new ObjectParameter("CODIGO_CIUDAD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_VENDEDOR", cODIGO, nOMBREParameter, aPELLIDOParameter, nUMERO_IDENTIFICACIONParameter, cODIGO_CIUDADParameter);
        }
    
        public virtual ObjectResult<lst_CIUDAD_Result> lst_CIUDAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lst_CIUDAD_Result>("lst_CIUDAD");
        }
    
        public virtual ObjectResult<lst_VENDEDOR_Result> lst_VENDEDOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lst_VENDEDOR_Result>("lst_VENDEDOR");
        }
    
        public virtual int upd_CIUDAD(Nullable<int> cODIGO, string dESCRIPCION)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_CIUDAD", cODIGOParameter, dESCRIPCIONParameter);
        }
    
        public virtual int upd_VENDEDOR(Nullable<int> cODIGO, string nOMBRE, string aPELLIDO, Nullable<long> nUMERO_IDENTIFICACION, Nullable<int> cODIGO_CIUDAD)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            var nUMERO_IDENTIFICACIONParameter = nUMERO_IDENTIFICACION.HasValue ?
                new ObjectParameter("NUMERO_IDENTIFICACION", nUMERO_IDENTIFICACION) :
                new ObjectParameter("NUMERO_IDENTIFICACION", typeof(long));
    
            var cODIGO_CIUDADParameter = cODIGO_CIUDAD.HasValue ?
                new ObjectParameter("CODIGO_CIUDAD", cODIGO_CIUDAD) :
                new ObjectParameter("CODIGO_CIUDAD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_VENDEDOR", cODIGOParameter, nOMBREParameter, aPELLIDOParameter, nUMERO_IDENTIFICACIONParameter, cODIGO_CIUDADParameter);
        }
    }
}
