//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public long NUMERO_IDENTIFICACION { get; set; }
        public int CODIGO_CIUDAD { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
    }
}
