CREATE DATABASE Ecommerce;

USE [Ecommerce]
GO
CREATE TABLE CIUDAD (
    CODIGO INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    DESCRIPCION NVARCHAR(20) NOT NULL,
);
GO
CREATE TABLE VENDEDOR (
    CODIGO INT NOT NULL IDENTITY(10, 10) PRIMARY KEY,
    NOMBRE NVARCHAR(20) NOT NULL,
	APELLIDO NVARCHAR(20) NOT NULL,
	NUMERO_IDENTIFICACION BIGINT NOT NULL,
	CODIGO_CIUDAD INT NOT NULL
	FOREIGN KEY(CODIGO_CIUDAD) REFERENCES CIUDAD(CODIGO)
);
GO