CREATE DATABASE Ecommerce;

USE [Ecommerce]
GO
CREATE TABLE CIUDAD (
    CODIGO INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    DESCRIPCION NVARCHAR(20) NOT NULL,
);
GO
CREATE TABLE VENDEDOR (
    CODIGO INT NOT NULL IDENTITY(10, 10) PRIMARY KEY,
    NOMBRE NVARCHAR(20) NOT NULL,
	APELLIDO NVARCHAR(20) NOT NULL,
	NUMERO_IDENTIFICACION BIGINT NOT NULL,
	CODIGO_CIUDAD INT NOT NULL
	FOREIGN KEY(CODIGO_CIUDAD) REFERENCES CIUDAD(CODIGO)
);
GO
	INSERT INTO CIUDAD VALUES ('Bogotá');
	INSERT INTO CIUDAD VALUES ('Cali');

	INSERT INTO VENDEDOR (NOMBRE, APELLIDO, NUMERO_IDENTIFICACION, CODIGO_CIUDAD) VALUES ('JUAN', 'POLANCO', 1111111111, 1);
	INSERT INTO VENDEDOR (NOMBRE, APELLIDO, NUMERO_IDENTIFICACION, CODIGO_CIUDAD) VALUES ('PEDRO', 'REYES', 2222222222, 2);
	INSERT INTO VENDEDOR (NOMBRE, APELLIDO, NUMERO_IDENTIFICACION, CODIGO_CIUDAD) VALUES ('MARIA', 'PAZ', 3333333333, 1);
	INSERT INTO VENDEDOR (NOMBRE, APELLIDO, NUMERO_IDENTIFICACION, CODIGO_CIUDAD) VALUES ('LUNA', 'MONROY', 4444444444, 1);
GO
	SELECT * FROM CIUDAD ORDER BY DESCRIPCION;
	SELECT * FROM VENDEDOR ORDER BY NOMBRE, APELLIDO;
GO